name: lagence2.com
analytics:
  google: UA-56034361-1
content_rating:
  adult: false
github: true
description: web design à Sion
opengraph:
  appId: ''
title: lagence2.com
author:
  name: Erwann
  url: www.lagence2.com
  email: ed@lagence2.com
color:
  lightness: 0.7383333327570775
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  saturation: 0.1887220426436332
  brandStrength: 0.02775950707210216
  rhythmicContrast: 0.1282637638804185
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c4c5152c-2a80-453a-9153-78a1081524e6.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c4c5152c-2a80-453a-9153-78a1081524e6.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
layout_spectrum: 0.5
typography_spectrum: 0.5
purpose:
  - type: contact
    url: 'mailto:ed@lagence2.com'
    label: Demandez votre devis !
logo: null
