name: lagence2.com
analytics:
  google: UA-56034361-1
content_rating:
  adult: false
github: true
description: web design à Sion
opengraph:
  appId: ''
title: lagence2.com
author:
  name: Erwann
  url: www.lagence2.com
  email: ed@lagence2.com
color:
  lightness: 0.7383333327570775
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  saturation: 0.1887220426436332
  brandStrength: 0.02775950707210216
  rhythmicContrast: 0.1282637638804185
content: []
layout_spectrum: 0.5
typography_spectrum: 0.5
purpose:
  - type: contact
    url: 'mailto:ed@lagence2.com'
    label: Demandez votre devis !
logo: null
