typography_spectrum: 0.5
content_rating:
  adult: false
color:
  lightness: 0.7383333327570775
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  saturation: 0.1887220426436332
  brandStrength: 0.02775950707210216
  rhythmicContrast: 0.1282637638804185
github: true
opengraph:
  appId: ''
layout_spectrum: 0.5
analytics:
  google: UA-56034361-1
author:
  name: Erwann
  url: www.lagence2.com
  email: ed@lagence2.com
logo: null
name: lagence2.com
navigation:
  - name: À propos
    id: 2389b0dd-54fc-4993-be10-e13cd0e590b3
    type: content
  - name: Contact
    id: b0a326f0-4d6e-4460-bf4d-50bd48d5313c
    type: content
title: lagence2.com
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c4c5152c-2a80-453a-9153-78a1081524e6.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c4c5152c-2a80-453a-9153-78a1081524e6.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: web design à Sion
purpose:
  - type: contact
    url: 'mailto:ed@lagence2.com'
    label: Contact
  - type: contact
    url: 'tel:0041768012609'
    label: Appel
