name: lagence2.com
analytics: {}
content_rating:
  adult: false
github: true
description: web design à Sion
opengraph: {}
title: lagence2.com
author:
  name: Erwann
  url: www.lagence2.com
  email: ed@lagence2.com
color:
  lightness: 0.7383333327570775
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  saturation: 0.1887220426436332
  brandStrength: 0.02775950707210216
  rhythmicContrast: 0.1282637638804185
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/aa2a9d87-28d7-47eb-beae-e8f2f7eae661.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/aa2a9d87-28d7-47eb-beae-e8f2f7eae661.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
